#!/usr/bin/env python3
"""Gather one language's tables into the one thing the engine knows it by.

Every other lifter writes a pile of tables and names each of them after the
language, so that two languages can be linked into one program. Nothing in
the engine looks any of those up by name: it goes through a delta_language,
and this writes that -- a page of externs and a struct, which is why it
reads nothing and needs no objects.

It writes the empty table of rules-written-as-C beside it, because that is
per language too and an ordinary build wants one for each.

usage: tools/module/gather.py <tag> [outdir]
"""

import os
import sys

# tools/evv.py says where the tree is, so that no tool counts directories to
# find it. The one thing this line has to know is that the directory above a
# tool's group is tools itself.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from evv import ROOT

PROCS = ("start", "end", "flush", "process_sentences", "process_remaining",
         "main")

# What a language is called where a person has to choose one. The tag is what
# the tree calls it and the number is IBM's; this is the third thing and it is
# ours, because nothing in the objects says "German" in so many words. A
# language not named here is offered under its tag.
NAMES = {
    "enus": "US English",
    "engb": "British English",
    "eses": "Castilian Spanish",
    "esus": "Latin American Spanish",
    "frfr": "French",
    "frca": "Canadian French",
    "dede": "German",
    "itit": "Italian",
    "jajp": "Japanese",
    # Ours rather than IBM's: family seventeen. The three tables indexed by
    # family hold eighteen, IBM used six, and four more -- 6, 10, 11 and 16 --
    # are families its own code says have a romanizer, so an instance of one of
    # those is refused outright when the romanizer is not there. Seventeen is
    # clear of all of it.
    "plpl": "Polish",
    "ukua": "Ukrainian",
}

LANG_C = '''/* Generated by tools/module/gather.py. Do not edit.

   %(tag)s as one table, which is the only name the engine knows it by.
   Everything below is defined by one of the generated files beside this,
   under a name carrying the language, because a program may have several
   languages in it and IBM gave the tables the same names in every module.
   src/delta/delta_lang.h says how the engine reaches whichever is in force. */

#include "delta.h"
#include "delta_rules_c.h"
#include "delta_rules_%(tag)s.h"

extern const int32_t %(tag)s_eci_library_lang;
extern const char    %(tag)s_eci_library_name[];
extern const char    %(tag)s_eciIni[];
extern const int32_t %(tag)s_eciIniSize;
extern const int32_t %(tag)s_delta_state_bytes;

extern const int8_t              %(tag)s_delta_globals[];
extern const int32_t             %(tag)s_delta_globals_n;
extern const delta_compound_decl %(tag)s_delta_compounds[];

extern delta_stmt %(tag)s_vstmtbl[];
extern void       %(tag)s_viasizes(void);

extern void %(tag)s_link_new(delta_state *d);
extern void %(tag)s_link_delete(delta_state *d);
extern void %(tag)s_set_dict_new(delta_state *d);
extern void %(tag)s_set_dict_delete(delta_state *d);
extern void %(tag)s_act_dict_new(delta_state *d);
extern void %(tag)s_act_dict_delete(delta_state *d);

extern const delta_rule_c *const %(tag)s_delta_rule_native[];

extern const delta_store %(tag)s_delta_authored_store[];

extern const delta_codepoint %(tag)s_delta_codepoints[];
extern const int32_t %(tag)s_delta_codepoints_n;

/* The two slots the runtime fills in for this language: the symbol table,
   once delta_syms_bind has copied the stores into the arena, and the index
   of whichever rules are written as C. Not const, unlike everything else
   here, which is why the language holds their addresses. */
const int32_t *%(tag)s_delta_sym_ref;
delta_rule_cfn *%(tag)s_delta_native_index;

/* The five entries the engine drives a machine through are rules, so the
   shim declares each taking the machine as a value, the way every rule
   does. The engine holds a pointer, so each gets a wrapper of the shape it
   holds them in rather than a cast that would be a lie on a host where a
   pointer is wider than a value. */
%(procdecls)s
%(procs)s
/* Not const, because the numbers below cannot go in an initialiser: each
   lives in another file as a const object, which C does not count as a
   constant expression. delta_lang_bind_%(tag)s fills them in once, before
   anything asks the language anything. */
delta_language delta_lang_%(tag)s = {
    "%(tag)s",
    "%(name)s",
    0, 0, 0,             /* id, library name, how big a machine is */

    /* The bytecode, the constants it names and the tables it jumps
       through. Nothing but the interpreter ever reads them, so a build with
       every rule written as C says nought here rather than naming them --
       which is what lets the linker drop the megabyte and a half they come
       to. The rule table below stays: it carries the names and the shapes,
       which both forms want. */
#ifdef EVV_NO_BYTECODE
    0, 0, 0,
#else
    %(tag)s_delta_rule_code,
    %(tag)s_delta_rule_imm,
    %(tag)s_delta_rule_map,
#endif
    %(tag)s_delta_rule_entry,
    %(tag)s_delta_rule_argmask,
    %(tag)s_delta_rule_entry_name,
    %(tag)s_delta_rule_sym,
    0,                   /* how many of those */
    %(tag)s_delta_rules,
    0, 0,                /* how many, and which one plants a landing place */
    DELTA_RULE_FRAME_MAX,
    %(tag)s_delta_rule_native,
    &%(tag)s_delta_native_index,

    %(tag)s_delta_const_store,
    %(tag)s_delta_authored_store,
    %(tag)s_delta_codepoints,
    0,                   /* how many of those */
    &%(tag)s_delta_sym_ref,

    %(tag)s_vstmtbl,
    %(tag)s_viasizes,

    %(tag)s_delta_globals,
    0,                   /* how many */
    %(tag)s_delta_compounds,

    %(tag)s_link_new,
    %(tag)s_link_delete,
    %(tag)s_set_dict_new,
    %(tag)s_set_dict_delete,
    %(tag)s_act_dict_new,
    %(tag)s_act_dict_delete,

%(procnames)s
    0, 0,                /* the settings blob and its size */
};

void delta_lang_bind_%(tag)s(void)
{
    delta_language *l = &delta_lang_%(tag)s;

    l->id             = %(tag)s_eci_library_lang;
    l->library_name   = %(tag)s_eci_library_name;
    l->state_bytes    = %(tag)s_delta_state_bytes;
    l->rule_sym_count = %(tag)s_delta_rule_sym_count;
    l->rule_count     = %(tag)s_delta_rule_count;
    l->rule_setjmp    = %(tag)s_delta_rule_setjmp;
    l->globals_n      = %(tag)s_delta_globals_n;
    l->codepoints_n   = %(tag)s_delta_codepoints_n;
    l->ini            = %(tag)s_eciIni;
    l->ini_size       = %(tag)s_eciIniSize;
}
'''

PROCDECL = "extern int32_t %(tag)s_DeltaProc_%(name)s(int32_t d);\n"

PROC = '''static int32_t proc_%(name)s(delta_state *d)
{
    return %(tag)s_DeltaProc_%(name)s(EVV_REF(d));
}

'''

NONE_C = '''/* Generated by tools/module/gather.py. Do not edit.

   No rules of %(tag)s written as C, so every one of them runs as bytecode.

   The interpreter looks in this table before it runs a rule and takes what
   it finds there instead. The table it looks in is either this one, which
   is empty, or the one tools/rules/decompile.py writes, which holds all of
   them. Both speak the same samples; the difference is a dozen megabytes of
   C and several minutes of compiler, so the empty one is what an ordinary
   build links and `make RULES=c' is what asks for the other. */

#include "delta_rules_c.h"

static const delta_rule_c none[] = {
    { -1, 0 },
};

const delta_rule_c *const %(tag)s_delta_rule_native[] = {
    none,
    0,
};
'''


AUTHORED_C = '''/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, which %(tag)s has none of. The
   lifted ones are in delta_consts_%(tag)s.c, generated out of IBM's objects;
   these are kept apart so that running that lifter again cannot lose them.

   Whatever is here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and
   an address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

const delta_store %(tag)s_delta_authored_store[] = {
    { 0, 0 },
};
'''


def main(argv):
    if not argv:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    tag = argv[0]
    out = argv[1] if len(argv) > 1 else os.path.join(ROOT, "lang", tag)
    os.makedirs(out, exist_ok=True)

    fields = {
        "tag": tag,
        "up": tag.upper(),
        "name": NAMES.get(tag, tag),
        "procdecls": "".join(PROCDECL % {"tag": tag, "name": n}
                             for n in PROCS),
        "procs": "".join(PROC % {"tag": tag, "name": n} for n in PROCS),
        "procnames": "".join("    proc_%s,\n" % n for n in PROCS),
    }

    with open(os.path.join(out, "delta_lang_%s.c" % tag), "w") as f:
        f.write(LANG_C % fields)

    with open(os.path.join(out, "delta_rules_none_%s.c" % tag), "w") as f:
        f.write(NONE_C % {"tag": tag})

    # Only if there is not one already: this is the one file in a module that
    # something other than a lifter writes, and overwriting it would throw
    # away every constant a rule of ours names.
    authored = os.path.join(out, "delta_authored_%s.c" % tag)
    if not os.path.exists(authored):
        with open(authored, "w") as f:
            f.write(AUTHORED_C % {"tag": tag})

    print("written to %s" % os.path.relpath(out, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
