/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/ukua/rules/constants.
   The lifted ones are in delta_consts_ukua.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t ukua_evv_authored_data[] = {
    /* pol_letter_aogonek, 1 bytes at 0 */
    207,
    /* pol_letter_cacute, 1 bytes at 1 */
    208,
    /* pol_letter_eogonek, 1 bytes at 2 */
    209,
    /* pol_letter_lstroke, 1 bytes at 3 */
    210,
    /* pol_letter_nacute, 1 bytes at 4 */
    211,
    /* pol_letter_sacute, 1 bytes at 5 */
    212,
    /* pol_letter_zacute, 1 bytes at 6 */
    213,
    /* pol_letter_zdot, 1 bytes at 7 */
    214,
    /* pol_ph_on, 2 bytes at 8 */
    33,18,
    /* pol_ph_en, 2 bytes at 10 */
    29,18,
    /* pol_ph_tsz, 2 bytes at 12 */
    4,24,
    /* pol_ph_dzz, 2 bytes at 14 */
    3,22,
    /* pol_name_cacute, 3 bytes at 16 */
    12,3,2,
    /* pol_name_lstroke, 2 bytes at 19 */
    2,210,
    /* pol_name_nacute, 2 bytes at 21 */
    2,211,
    /* pol_name_sacute, 2 bytes at 23 */
    2,212,
    /* pol_name_zacute, 4 bytes at 25 */
    31,3,2,26,
    /* pol_name_zdot, 3 bytes at 29 */
    214,2,26,
    /* pol_name_a, 1 bytes at 32 */
    1,
    /* pol_name_b, 2 bytes at 33 */
    11,2,
    /* pol_name_c, 2 bytes at 35 */
    12,2,
    /* pol_name_d, 2 bytes at 37 */
    13,2,
    /* pol_name_e, 1 bytes at 39 */
    2,
    /* pol_name_f, 2 bytes at 40 */
    2,14,
    /* pol_name_g, 3 bytes at 42 */
    15,3,2,
    /* pol_name_h, 2 bytes at 45 */
    16,1,
    /* pol_name_i, 1 bytes at 47 */
    3,
    /* pol_name_j, 3 bytes at 48 */
    17,4,26,
    /* pol_name_k, 2 bytes at 51 */
    18,1,
    /* pol_name_l, 2 bytes at 53 */
    2,19,
    /* pol_name_m, 2 bytes at 55 */
    2,20,
    /* pol_name_n, 2 bytes at 57 */
    2,21,
    /* pol_name_o, 1 bytes at 59 */
    4,
    /* pol_name_p, 2 bytes at 60 */
    22,2,
    /* pol_name_q, 2 bytes at 62 */
    18,5,
    /* pol_name_r, 2 bytes at 64 */
    2,24,
    /* pol_name_s, 2 bytes at 66 */
    2,25,
    /* pol_name_t, 2 bytes at 68 */
    26,2,
    /* pol_name_u, 1 bytes at 70 */
    5,
    /* pol_name_v, 3 bytes at 71 */
    14,1,28,
    /* pol_name_w, 2 bytes at 74 */
    28,5,
    /* pol_name_x, 3 bytes at 76 */
    3,18,25,
    /* pol_name_y, 5 bytes at 79 */
    3,15,24,2,18,
    /* pol_name_z, 3 bytes at 84 */
    31,2,26,
    /* pol_num_2, 3 bytes at 87 */
    13,28,1,
    /* pol_num_3, 4 bytes at 90 */
    26,24,31,30,
    /* pol_num_4, 6 bytes at 94 */
    12,31,26,2,24,30,
    /* pol_num_5, 4 bytes at 100 */
    22,3,209,208,
    /* pol_num_6, 5 bytes at 104 */
    25,31,2,212,208,
    /* pol_num_7, 6 bytes at 109 */
    25,3,2,13,2,20,
    /* pol_num_8, 5 bytes at 115 */
    4,25,3,2,20,
    /* pol_num_9, 8 bytes at 120 */
    13,31,3,2,28,3,209,208,
    /* pol_num_10, 8 bytes at 128 */
    13,31,3,2,25,3,209,208,
    /* pol_num_11, 10 bytes at 136 */
    17,2,13,2,21,1,212,12,3,2,
    /* pol_num_12, 9 bytes at 146 */
    13,28,1,21,1,212,12,3,2,
    /* pol_num_13, 10 bytes at 155 */
    26,24,31,30,21,1,212,12,3,2,
    /* pol_num_14, 11 bytes at 165 */
    12,31,26,2,24,21,1,212,12,3,2,
    /* pol_num_15, 10 bytes at 176 */
    22,3,209,26,21,1,212,12,3,2,
    /* pol_num_16, 10 bytes at 186 */
    25,31,2,25,21,1,212,12,3,2,
    /* pol_num_17, 12 bytes at 196 */
    25,3,2,13,2,20,21,1,212,12,3,2,
    /* pol_num_18, 11 bytes at 208 */
    4,25,3,2,20,21,1,212,12,3,2,
    /* pol_num_19, 14 bytes at 219 */
    13,31,3,2,28,3,209,26,21,1,212,12,3,2,
    /* pol_num_20, 12 bytes at 233 */
    13,28,1,13,31,3,2,212,12,3,1,72,
    /* pol_num_30, 12 bytes at 245 */
    26,24,31,30,13,31,3,2,212,12,3,72,
    /* pol_num_40, 13 bytes at 257 */
    12,31,26,2,24,13,31,3,2,212,12,3,72,
    /* pol_num_50, 13 bytes at 270 */
    22,3,209,208,13,31,3,2,25,3,207,26,72,
    /* pol_num_60, 14 bytes at 283 */
    25,31,2,212,208,13,31,3,2,25,3,207,26,72,
    /* pol_num_70, 15 bytes at 297 */
    25,3,2,13,2,20,13,31,3,2,25,3,207,26,72,
    /* pol_num_80, 14 bytes at 312 */
    4,25,3,2,20,13,31,3,2,25,3,207,26,72,
    /* pol_num_90, 17 bytes at 326 */
    13,31,3,2,28,3,209,208,13,31,3,2,25,3,207,26,
    72,
    /* pol_num_1, 5 bytes at 343 */
    17,2,13,2,21,
    /* pol_num_100, 3 bytes at 348 */
    25,26,4,
    /* pol_num_100j, 4 bytes at 351 */
    199,25,2,26,
    /* pol_num_1000, 6 bytes at 355 */
    26,30,25,3,207,12,
    /* pol_num_1000j, 9 bytes at 361 */
    199,72,26,30,25,3,207,12,2,
    /* pol_num_mln, 8 bytes at 370 */
    199,72,20,3,19,3,4,21,
    /* pol_num_mlns, 9 bytes at 378 */
    199,72,20,3,19,3,4,21,30,
    /* pol_num_mld, 9 bytes at 387 */
    199,72,20,3,19,3,1,24,13,
    /* pol_num_mlds, 10 bytes at 396 */
    199,72,20,3,19,3,1,24,13,30,
    /* pol_num_and, 2 bytes at 406 */
    199,72,
    /* pol_ph_aogonek, 1 bytes at 408 */
    35,
    /* pol_letter_p, 1 bytes at 409 */
    22,
    /* pol_letter_t, 1 bytes at 410 */
    26,
    /* pol_letter_k, 1 bytes at 411 */
    18,
    /* pol_letter_f, 1 bytes at 412 */
    14,
    /* pol_letter_s, 1 bytes at 413 */
    25,
    /* pol_letter_c, 1 bytes at 414 */
    12,
    /* pol_letter_h, 1 bytes at 415 */
    16,
    /* pol_ph_x, 1 bytes at 416 */
    36,
    /* ukua_let_a, 1 bytes at 417 */
    102,
    /* ukua_let_b, 1 bytes at 418 */
    112,
    /* ukua_let_v, 1 bytes at 419 */
    122,
    /* ukua_let_h, 1 bytes at 420 */
    129,
    /* ukua_let_g, 1 bytes at 421 */
    136,
    /* ukua_let_d, 1 bytes at 422 */
    142,
    /* ukua_let_e, 1 bytes at 423 */
    144,
    /* ukua_let_je, 1 bytes at 424 */
    152,
    /* ukua_let_zh, 1 bytes at 425 */
    103,
    /* ukua_let_z, 1 bytes at 426 */
    113,
    /* ukua_let_y, 1 bytes at 427 */
    123,
    /* ukua_let_i, 1 bytes at 428 */
    137,
    /* ukua_let_ji, 1 bytes at 429 */
    104,
    /* ukua_let_j, 1 bytes at 430 */
    114,
    /* ukua_let_k, 1 bytes at 431 */
    124,
    /* ukua_let_l, 1 bytes at 432 */
    138,
    /* ukua_let_m, 1 bytes at 433 */
    154,
    /* ukua_let_n, 1 bytes at 434 */
    156,
    /* ukua_let_o, 1 bytes at 435 */
    105,
    /* ukua_let_p, 1 bytes at 436 */
    115,
    /* ukua_let_r, 1 bytes at 437 */
    125,
    /* ukua_let_s, 1 bytes at 438 */
    130,
    /* ukua_let_t, 1 bytes at 439 */
    139,
    /* ukua_let_u, 1 bytes at 440 */
    148,
    /* ukua_let_f, 1 bytes at 441 */
    106,
    /* ukua_let_kh, 1 bytes at 442 */
    116,
    /* ukua_let_ts, 1 bytes at 443 */
    126,
    /* ukua_let_ch, 1 bytes at 444 */
    140,
    /* ukua_let_sh, 1 bytes at 445 */
    150,
    /* ukua_let_shch, 1 bytes at 446 */
    161,
    /* ukua_let_ju, 1 bytes at 447 */
    97,
    /* ukua_let_ja, 1 bytes at 448 */
    107,
    /* ukua_ph_a, 1 bytes at 449 */
    30,
    /* ukua_ph_b, 1 bytes at 450 */
    1,
    /* ukua_ph_v, 1 bytes at 451 */
    7,
    /* ukua_ph_h, 1 bytes at 452 */
    36,
    /* ukua_ph_g, 1 bytes at 453 */
    6,
    /* ukua_ph_d, 1 bytes at 454 */
    3,
    /* ukua_ph_e, 1 bytes at 455 */
    29,
    /* ukua_ph_je, 2 bytes at 456 */
    25,29,
    /* ukua_ph_zh, 1 bytes at 458 */
    11,
    /* ukua_ph_z, 1 bytes at 459 */
    9,
    /* ukua_ph_y, 1 bytes at 460 */
    27,
    /* ukua_ph_i, 1 bytes at 461 */
    27,
    /* ukua_ph_ji, 2 bytes at 462 */
    25,27,
    /* ukua_ph_j, 1 bytes at 464 */
    25,
    /* ukua_ph_k, 1 bytes at 465 */
    5,
    /* ukua_ph_l, 1 bytes at 466 */
    23,
    /* ukua_ph_m, 1 bytes at 467 */
    17,
    /* ukua_ph_n, 1 bytes at 468 */
    18,
    /* ukua_ph_o, 1 bytes at 469 */
    32,
    /* ukua_ph_p, 1 bytes at 470 */
    2,
    /* ukua_ph_r, 1 bytes at 471 */
    21,
    /* ukua_ph_s, 1 bytes at 472 */
    10,
    /* ukua_ph_t, 1 bytes at 473 */
    4,
    /* ukua_ph_u, 1 bytes at 474 */
    31,
    /* ukua_ph_f, 1 bytes at 475 */
    8,
    /* ukua_ph_kh, 1 bytes at 476 */
    36,
    /* ukua_ph_ts, 1 bytes at 477 */
    16,
    /* ukua_ph_ch, 1 bytes at 478 */
    14,
    /* ukua_ph_sh, 1 bytes at 479 */
    12,
    /* ukua_ph_shch, 2 bytes at 480 */
    12,14,
    /* ukua_ph_ju, 2 bytes at 482 */
    25,31,
    /* ukua_ph_ja, 2 bytes at 484 */
    25,30,
};

const delta_store ukua_delta_authored_store[] = {
    { ukua_evv_authored_data, sizeof ukua_evv_authored_data },
    { 0, 0 },
};
